spring:
  datasource:
    url: jdbc:sqlserver://specbackend-server.mysql.database.azure.com:3306;database=specbackend-server;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: lgjmjbznal
    password: 0206245NU8V31714$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


