spring:
  datasource:
    url: jdbc:sqlserver://specbackend-server.mysql.database.azure.com:3306/specbackend-server?useSSL=true
    username: lgjmjbznal
    password: 0206245NU8V31714$
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191


