spring:
  datasource:
    url: jdbc:sqlserver://spectrumdevops.database.windows.net:1433;database=spectrumdevops;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: spectrumdevops
    password: Password1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 9191




